### ISSUE TITLE
Data Overview

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#1]
As a **Developer** I can **have an overview of the dataset** so that **I can see features and target distributions and histograms**

# Tasks
- [x] Install ydataprofiling
- [x] Have a plot showing the distribution for each variable where possible
- [x] Have a summary of each variable

# Acceptance Criteria 
- [x] Have a plot showing variables distribution where possible
- [x] Have a summary describing each feature

# User Story score 2
