### ISSUE TITLE
Streamlit correlation page

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#10]
As a **User** I can **visualize the correlation page on Streamlit** so that **I can understand which features correlate the most with myocardial infarction risk**

# Tasks
- [x] Add correlation page to Streamlit
- [x] Add plots displaying how the feature which correlates the most correlate to myocardial infarction risk
- [x] Add a parallel plot displaying the phenotype of a patient at high risk of myocardial infarction

# Acceptance Criteria 
- [x] Features which correlate the most with myocardial infarction are visible on the Streamlit page
- [x] Plots to visualize the correlation are present on the Streamlit page

# User Story score 1
