### ISSUE TITLE
Streamlit Analysis page

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#11]
As a **User** I can **Insert patient data** so that **I can verify if the patient is at high risk of myocardial infarction**

# Tasks
- [x] Add a legend displaying the meaning and value of each feature
- [x] Add widgets to add value
- [x] Add button run pipeline on live data and display myocardial infarction risk

# Acceptance Criteria 
- [x] Values can be added through widgets
- [x] Features meaning and values are clear
- [x] Message display myocardial infarction risk is clear and visible

# User Story score 2
