### ISSUE TITLE
Streamlit ML pipeline evaluation page

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#12]
As a **User** I can **visualize pipeline performances** so that **I can evaluate if pipeline outputs can be trusted**

# Tasks
- [x] Add confusion matrix on the Streamlit page
- [x] Add a plot to visualize pipeline performances

# Acceptance Criteria 
- [x] Confusion matrix for test and train dataset is visible
- [x] A plot to immediately understand the performances of the pipeline is available on the Streamlit page

# User Story score 1
