### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#13]
As a **User** I can **get details of the project and ML pipeline implementation** so that **I can decide if to adopt it or not**

# Tasks
- [x] Add project intro
- [x] Add details on pipeline implementation
- [x] Add info on deployment is performed
- [x] Add a list of manual testing performed
- [x] Add a list of the most significant bugs encountered and solved

# Acceptance Criteria 
- [x] Documentation on how the ML pipeline has been developed is clear and readable
- [x] Info on the purpose of the project is clear
- [x] Manual testing is clear and visible

# User Story score 10
