### ISSUE TITLE
Neural Network implementation

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#14]
As a **Developer** I can **compare the regular ML approach to a neural network approach** so that **I can understand which one performs better**

# Tasks
- [x] Implement feature engineering for neural network
- [x] Implement neural network model
- [x] Fit neural network model
- [x] Evaluate neural network performances

# Acceptance Criteria 
- [x] Neural network model is present on Jupiter notebook
- [x] Confusion matrix is evaluated for neural network
- [x] Plot displaying loss and precision on test and validation data are present in Jupiter notebooks

# User Story score 7
