### ISSUE TITLE
Data Exploration

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#2]
As a **Developer** I can **understand which variable correlates the most with myocardial infarction** so that **I can meet one of the business requirements**

# Tasks
- [x] Evaluate Spearman coefficient
- [x] Evaluate Pearson coefficient
- [x] Evaluate Predictive Power Score(PPS) 

# Acceptance Criteria 
- [x] Display which features correlate the most according to the Spearman coefficient 
- [x] Display which features correlate the most according to the Pearson coefficient
- [x] Display which features have the highest PPS

# User Story score 4
