### ISSUE TITLE
Data Cleaning

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#3]
As a **Developer** I can **check if there are missing data in the dataset** so that **I can handle them**

# Tasks
- [x] Check for missing data
- [x] If missing data are present apply a strategy to handle them 

# Acceptance Criteria 
- [x] If missing data are present they are shown in the Jupiter Notebook
- [x] If missing data are handled, the strategy to handle them is shown in Jupiter's notebook

# User Story score 3
