### ISSUE TITLE
Dataset  import

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#4]
As a **Developer** I can **import the data into Jupiter Notebook** so that **I can process the dataset**

# Tasks
- [x] Install Kaggle library
- [x] Get the Kaggle JSON file
- [x] Download and unzip dataset

# Acceptance Criteria 
- [x] Kaggle library is installed
- [x] Dataset is downloaded
- [x] A Dataframe containing the dataset can be shown

# User Story score 1
