### ISSUE TITLE
Feature Engineering

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#5]
As a **Developer** I can **have a dataset containing engineered features** so that **ML pipeline can be applied**

# Tasks
- [x] Verify if outliers are present and handle them
- [x] Verify if there are categorical variables and turn them into numerical
- [x] Adjust feature values so that they are all on the same scale

# Acceptance Criteria 
- [x] Feature engineering steps are described in the notebook
- [x] A Feature engineering pipeline is created

# User Story score 5
