### ISSUE TITLE
ML pipeline

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#6]
As a **Developer** I can **run an ML pipeline** so that **I can predict myocardial infarction**

# Tasks
- [x] Find the best classifier
- [x] Get hyper parametrization
- [x] Fit the model
- [x] Save the pipeline

# Acceptance Criteria 
- [x] An ML pipeline to predict myocardial infarction is implemented
- [x] The pipeline is saved in the repository

# User Story score 5
