### ISSUE TITLE
Streamlit summary page

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#7]
As a **User** I can **visualize Streamlet's first page** so that **I can have an overview of the project aim and jargon**

# Tasks
- [x] Install Streamlit library
- [x] Create the first Streamlit page

# Acceptance Criteria 
- [x] A page containing a description of all the jargon terms is available
- [x] A description of the project aim and hypothesis is visible

# User Story score 4
