### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#8]
As a **Developer** I can **deploy my project on Heroku** so that **Users can visualize it and provide feedback**

# Tasks
- [x] Create Procfile
- [x] Make sure requirements.txt is up to date
- [x] Creare a new app on Heroku
- [x] Add local variables

# Acceptance Criteria 
- [x] Streamlit pages are visible on the Heroku platform

# User Story score 2
