### ISSUE TITLE
ML model evaluation

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/Heart_attack_risk#9]
As a **Developer** I can **assess the ML pipeline** so that **I can improve the model if business requirements are not met**

# Tasks
- [x] Evaluate confusion matrix for both test and train sets
- [x] Evaluate error rate
- [x] Creare a plot to show model performances

# Acceptance Criteria 
- [x] Confusion matrix related to ML model is displayed on Jupiter Notebook
- [x] Evaluation of error rate is present on Jupiter Notebook
- [x] A plot displaying the model performances is present on the Jupiter Notebook

# User Story score 3
